name: Build with nob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get deps
      run: sudo apt install xorg-dev
    - name: bootstrap
      run: cc -o nob nob.c
    - name: build
      run: ./nob
